<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

$this->placeHolder('MyContactForm')->captureStart('SET');

$this->plugin('formLabel')->setTranslatorTextDomain('MyContact');
$this->plugin('formInput')->setTranslatorTextDomain('MyContact');
$this->plugin('formTextarea')->setTranslatorTextDomain('MyContact');
$this->plugin('formElementErrors')->setTranslatorTextDomain('MyContact')->setAttributes(array('class' => 'error'));

/* @var \MyContact\Form\ContactForm $form */
$form = $this->contactForm;
$form->prepare();
$form->setAttribute('action', $this->url('contact/process'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->partial('my-contact/contact/form-fields', array('form' => $form));
echo $this->form()->closeTag();

$this->placeHolder('MyContactForm')->captureEnd();

if ($this->viewModel()->getCurrent()->terminate()) {
    echo $this->placeHolder('MyContactForm');

    return;
}

?>
<div class="form-wrapper">
    <?= $this->placeHolder('MyContactForm') ?>
</div>
